#[derive(Copy, Clone, Eq, PartialEq, Debug)]
pub enum AnnotationType {
    Match,
    SelectedMatch,
    Number,
    Keyword,
    Type,
    KnownValue,
    Char,
    LifetimeSpecifier,
    Comment,
    String,
    Variable,
    Function,
    Method,
    Operator,
    Punctuation,
    Property,
    Constant,
    Boolean,
    Macro,
    Attribute,
    Selection,
    Replacement,
}
